# Generated by Django 3.2.12 on 2022-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20220802_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypage',
            name='primary_tags',
        ),
        migrations.AddField(
            model_name='storypage',
            name='primary_tag',
            field=models.CharField(blank=True, choices=[('Recent Gifts & Milestones', 'Recent Gifts & Milestones'), ('Undergrad Scholarships', 'Undergrad Scholarships'), ('Graduate Fellowships', 'Graduate Fellowships'), ('Health & Wellness', 'Health & Wellness'), ('Career Advising', 'Career Advising'), ('Co-Curricular Experience', 'Co-Curricular Experience')], max_length=100, null=True),
        ),
    ]
