# Generated by Django 3.2.12 on 2022-08-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20220802_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimaryTag',
        ),
    ]
