# Generated by Django 3.2.12 on 2022-08-02 22:26

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('story', '0006_delete_primarytag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='secondary_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='story.StoryPageSecondaryTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='StoryPagePrimaryTag',
        ),
    ]
