# Generated by Django 3.2.12 on 2022-08-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20220802_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='story.author'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='co_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_author', to='story.author'),
        ),
    ]
