# Generated by Django 3.2.14 on 2022-08-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20220803_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoAuthor',
        ),
        migrations.RenameField(
            model_name='storypage',
            old_name='primary_tag',
            new_name='display_tags',
        ),
        migrations.RenameField(
            model_name='storypage',
            old_name='secondary_tags',
            new_name='tags',
        ),
    ]
