# Generated by Django 3.2.14 on 2022-08-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20220808_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypage',
            name='description',
        ),
    ]
