# Generated by Django 3.2.14 on 2022-08-09 14:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_auto_20220809_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_form_field', to='story.storypage'),
        ),
    ]
