# Generated by Django 3.2.14 on 2022-08-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_faqpage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqpage',
            old_name='content',
            new_name='links',
        ),
    ]
