# Generated by Django 3.2.14 on 2022-08-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_auto_20220812_1210'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0009_rename_faqs_faqspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesOfImpactHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_page1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_page1', to='story.storypage')),
                ('featured_page2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_page2', to='story.storypage')),
                ('featured_page3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_page3', to='story.storypage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
