# Generated by Django 3.2.14 on 2022-08-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0010_storiesofimpacthomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressAmount',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('initial_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('final_amt', models.IntegerField(blank=True, default=0, null=True)),
                ('percentage', models.CharField(blank=True, default='0%', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
