# Generated by Django 3.2.14 on 2022-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_progressamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressamount',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
