# Generated by Django 3.2.14 on 2022-08-15 16:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtailsvg.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
        ('home', '0014_svgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgs',
            name='summary',
        ),
        migrations.AddField(
            model_name='svgs',
            name='body',
            field=wagtail.core.fields.StreamField([('svg', wagtailsvg.blocks.SvgChooserBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='svgs',
            name='svg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
    ]
