# Generated by Django 3.2.14 on 2022-08-16 16:59

from django.db import migrations, models
import django.db.models.deletion
import story.blocks
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0017_svgpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillarsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PillarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', story.blocks.CustomImageChooserBlock(rendition='width-800'))])), ('image_carousel', wagtail.core.blocks.ListBlock(story.blocks.CustomImageChooserBlock())), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(story.blocks.CustomImageChooserBlock()))], blank=True, null=True)),
                ('summary', models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True)),
                ('sub_heading', models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
