# Generated by Django 3.2.14 on 2022-08-17 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0019_auto_20220817_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SVGPage',
            new_name='CTACards',
        ),
        migrations.AddField(
            model_name='progressamount',
            name='hero_headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
