# Generated by Django 3.2.14 on 2022-08-18 09:53

from django.db import migrations, models
import django.db.models.deletion
import story.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0022_auto_20220818_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('stats_headline', models.CharField(blank=True, max_length=100, null=True)),
                ('stats_copy', wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', story.blocks.CustomImageChooserBlock(rendition='width-800'))])), ('image_carousel', wagtail.core.blocks.ListBlock(story.blocks.CustomImageChooserBlock())), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(story.blocks.CustomImageChooserBlock()))], blank=True, null=True)),
                ('stats_cta', wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='svgs',
            name='stats_copy',
        ),
        migrations.RemoveField(
            model_name='svgs',
            name='stats_cta',
        ),
        migrations.RemoveField(
            model_name='svgs',
            name='stats_headline',
        ),
    ]
