# Generated by Django 3.2.14 on 2022-08-18 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0023_auto_20220818_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='StatsSVG',
        ),
    ]
