# Generated by Django 3.2.14 on 2022-08-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0025_imagecta_image_cta_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillarpage',
            name='sub_heading',
        ),
        migrations.AddField(
            model_name='pillarpage',
            name='dollars_raised',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pillarpage',
            name='percent_to_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pillarpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
