# Generated by Django 3.2.14 on 2022-08-18 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0019_auto_20220812_1210'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0026_auto_20220818_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoriesOfImpactHomePage',
            new_name='CardsCTA',
        ),
    ]
