# Generated by Django 3.2.14 on 2022-08-18 11:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_storiesofimpacthomepage_cardscta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardscta',
            name='cards_cta',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=True))]))], blank=True, null=True),
        ),
    ]
