# Generated by Django 3.2.14 on 2022-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20220818_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresshero',
            name='final_amt',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progresshero',
            name='initial_amt',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progresshero',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
