# Generated by Django 3.2.14 on 2022-08-19 10:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_auto_20220812_1210'),
        ('home', '0031_auto_20220818_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillarpage',
            name='pillar_featured_page1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pillar_featured_page1', to='story.storypage'),
        ),
        migrations.AddField(
            model_name='pillarpage',
            name='pillar_featured_page2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pillar_featured_page2', to='story.storypage'),
        ),
        migrations.AddField(
            model_name='pillarpage',
            name='pillar_featured_page3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pillar_featured_page3', to='story.storypage'),
        ),
        migrations.AddField(
            model_name='pillarpage',
            name='pillars_cta',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=True))]))], blank=True, null=True),
        ),
    ]
