# Generated by Django 3.2.14 on 2022-08-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0035_delete_pillarspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PillarPage',
        ),
    ]
