# Generated by Django 3.2.14 on 2022-08-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_delete_pillarpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresshero',
            name='video_embed',
        ),
        migrations.AddField(
            model_name='progresshero',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
    ]
