# Generated by Django 3.2.14 on 2022-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20220822_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresshero',
            name='show_video_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
