# Generated by Django 3.2.14 on 2022-08-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillars', '0005_pillarpages_show_dollars_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillarpages',
            name='pillars_featured_page1',
        ),
        migrations.RemoveField(
            model_name='pillarpages',
            name='pillars_featured_page2',
        ),
        migrations.RemoveField(
            model_name='pillarpages',
            name='pillars_featured_page3',
        ),
    ]
